-- JET Gestao de Obras - Catalogo de materiais + Regras de miudezas + Markups por obra
-- Gerado das planilhas (CCI + Planilha Unificada). Rodar no SQL Editor do Supabase.
-- Seguro para rodar mais de uma vez (cria se nao existir + upsert do seed).

begin;

create table if not exists public.catalogo_materiais (
  id bigint generated always as identity primary key,
  descricao text not null unique,
  unidade text,
  mat_unit numeric,
  mobra_unit numeric,
  classe_custo text,
  secao text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.miudezas_regras (
  id bigint generated always as identity primary key,
  material_base text not null,
  miudeza text not null,
  tipo_verba text,
  coef numeric,
  valor_unit numeric,
  usar boolean not null default true,
  sistema text,
  familia text,
  unique (material_base, miudeza, tipo_verba)
);

create table if not exists public.obra_markups (
  obra text primary key,
  ipi numeric not null default 0,
  st numeric not null default 0,
  adm numeric not null default 45,
  updated_at timestamptz not null default now()
);

alter table public.aditivos add column if not exists markups jsonb;

do $$
declare tbl text; tables text[] := array['catalogo_materiais','miudezas_regras','obra_markups'];
begin
  foreach tbl in array tables loop
    execute format('alter table public.%I enable row level security', tbl);
    execute format('drop policy if exists "jet_auth_read_%s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "jet_auth_insert_%s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "jet_auth_update_%s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "jet_auth_delete_%s" on public.%I', tbl, tbl);
    execute format('create policy "jet_auth_read_%s" on public.%I for select to authenticated using (auth.role() = ''authenticated'')', tbl, tbl);
    execute format('create policy "jet_auth_insert_%s" on public.%I for insert to authenticated with check (auth.role() = ''authenticated'')', tbl, tbl);
    execute format('create policy "jet_auth_update_%s" on public.%I for update to authenticated using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')', tbl, tbl);
    execute format('create policy "jet_auth_delete_%s" on public.%I for delete to authenticated using (auth.role() = ''authenticated'')', tbl, tbl);
  end loop;
end $$;

insert into public.catalogo_materiais (descricao,unidade,mat_unit,mobra_unit,classe_custo,secao) values
('Acessórios complemetares da subestação (Tapete 20Kv, luvas MT 20Kv NR-10, sinalização, etc...)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Acessórios e conexões para Condulete (Unidut, bucha e arruela, tampa, etc...)','vb',437.65,218.825,null,null),
('Acessórios e conexões para eletrocalha (curvas verticais, curvas horizontais, tês, flanges, talas de emenda, saída horizontal para perfilado 38 x 38, saída horizontal para eletroduto 3/4", etc...)','vb',527.04,263.52,null,null),
('Acessórios e conexões para eletroduto (Curva, bucha e arruela, unidut, luva,box, etc...)','vb',437.65,218.825,null,null),
('Acessórios e conexões para perfilado (junção tipo "I", junção tipo "L", junção tipo "T", junção tipo "X", saída lateral para eletroduto 3/4", etc...)','vb',2275.44,1133.74,null,null),
('Acessórios para cabos (Terminais de compressão, fitas isolantes, fita crepe, solda estanho, identificações, etc...)','vb',260.89,130.445,null,null),
('Acessórios para fiação (fitas isolantes, fita crepe, solda estanho, identificações, etc...)','vb',1253.38,626.69,null,null),
('Acessórios para interruptores e tomadas (Espelhos, tampas, placas, parafusos, etc...)','vb',458.9,229.45,null,null),
('Acessórios para montagem da lâmpada (Soquete para lâmpadas fluorescente T5, Abraçadeira T5, Cabos para montagem do reator, etc...)','vb',587.05,293.525,null,null),
('Acessórios para montagem de D.G (Blocos BLI, conectores, etc...)','vb',null,null,null,null),
('Acessórios para montagem dos quadros (Terminais de compressão,pino, garfo, fitas isolantes, fita crepe, solda estanho, identificações, etc...)','vb',1520.0,760.0,null,null),
('Acessórios para tomadas (Espelhos, tampas, placas, parafusos, etc...)','vb',727.58,363.79,null,null),
('Acionador manual tipo quebra-vidro, inclusive base e demais acessórios','pç',null,null,null,null),
('Acompanhamento e apoio ao tecnico do grupo gerador Incluindo fornecimento de (10Mts de mangueira trançada de 3/8" 250PSI, 100Lts de óleo diesel, montagem do escapamento, óleo lubrificante, etc...)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Acompanhamento e apoio ao tecnico do no-break (star-up)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Acompanhamento e apoio ao técnic do sistema de sonorização, CFTV, Contagem de fluxo)','vb',1.0,1750.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Acompanhamento e comissionamento da ligação elétrica definitiva','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Adaptadores PVC marrom ( Ø 25 mm X3/4", Ø 32 mm X 1", Ø 40 mm X 1.1/4", Ø 50 mm X 1.1/2", Ø 60 mm X 2", Etc...)','vb',null,null,null,null),
('Adequação e aprovação dos projetos de combate a incêndio no CB local','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Adesivos  e marcação de restrição de área','vb',389.7,194.85,null,null),
('Administrativo/Almoxarife',null,33.6,null,'224650','1.0 Homem/Hora'),
('Alimentação e estadia','vb',4.0,24700.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Anel de Borracha','vb',null,null,null,null),
('ARANDELA (MINIMATRIX) BORDA DE SANCA','pç',32.5,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('ART Contemplanto todos os serviços executados','vb',1.0,1250.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Aterramento da subestação e transformador (Cabos, Cordoalhas, conectores, e demais acessórios)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Auxiliar Eletricista',null,34.8,null,'224650','1.0 Homem/Hora'),
('Auxiliar Hidraulico',null,34.8,null,'224650','1.0 Homem/Hora'),
('Bacia sanitária com caixa acoplada de duplo acionamento com assento','pç',null,null,null,null),
('Barramento tipo varão de cobre, de 3/8", inclusive conexões','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Bebedouro elétrico, com com filtro anexo - somente mão-de-obra','pç',null,null,null,null),
('Bloco autônomo 2x55W autonomia de 1 hora, instalado na subestação','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Bloco autônomo com luminária de indicação de saída','pç',286.53,171.918,null,null),
('Bloco luminária autônoma para iluminação de emergência 2x55W','pç',null,null,null,null),
('Bloco luminária autônoma para iluminação de emergência 2x9W','pç',67.79,40.674,null,null),
('Bloco luminária autônoma para iluminação de emergência 2x9W realocado','pç',null,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('Botoeira iluminação vigia','pç',null,null,null,null),
('BOURBON SHOPPING POMPEIA',null,null,null,null,null),
('CABO 4X22BR 2 PARES 0,30mm² FLEX','m',11.24,6.744,null,null),
('Cabo blindado 2 x 24AWG','m',null,null,null,null),
('Cabo blindado 2x1,5mm2 / 750V - a confirmar com fornecedor da central de alarme','m',9.87,5.922,null,null),
('Cabo CCI-50 2 Pares','m',null,null,null,null),
('Cabo CCI-50 20 Pares','m',null,null,null,null),
('Cabo coaxial RG 59 - 75 ohms 93% malha','m',null,null,null,null),
('Cabo coaxial RG 59 - 75 ohms 93% malha (Câmera de Contador de fluxo até o Rack de lógica)','m',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Cabo cobre isolação 750V #10mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #120mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #16mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #2,5mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #25mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #35mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #4mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #50mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #6mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #70mm²','m',null,null,null,null),
('Cabo cobre isolação 750V #95mm²','m',null,null,null,null),
('Cabo cobre isolação afumex 0,6/1000V #10mm²','m',null,null,null,null),
('Cabo cobre isolação afumex 750V #2,5mm²','m',4.02,2.01,null,null),
('Cabo cobre isolação afumex 750V #4mm²','m',6.53,3.265,null,null),
('Cabo cobre isolação afumex 750V #6mm²','m',null,null,null,null),
('Cabo de cobre afumex tipo PP 3x#2,5m²','m',8.43,4.215,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #10mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #120mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #150mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #16mm²','m',27.48,10.992,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #185mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #2,5mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #240mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #25mm²','m',42.18,23.199,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #35mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #4mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #50mm²','m',83.98,46.189,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #6mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #70mm²','m',null,null,null,null),
('Cabo de cobre isolação 0,6/1kV 90º EPR #95mm²','m',null,null,null,null),
('Cabo UTP cat. 5E - Azul - 305mts',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Cabo UTP cat. 5E - cinza - 305mts',null,800.0,400.0,null,null),
('Caixa 4x2" com espelho cego','pç',null,null,null,null),
('Caixa com barra de equipotencialidade','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Caixa de gordura em PVC  18 litros - Amanco ou Tigre','pç',null,null,null,null),
('Caixa de hidrante dupla com (mangueiras, esguichos fixo, regulável, adaptador, chave, tampão cego, registro globo angulhar 45° de 2.1/2" e demais e acessórios)','pç',null,null,null,null),
('Caixa de hidrante simples com (mangueiras, esguichos fixo, regulável, adaptador, chave, tampão cego, registro globo angulhar 45° de 2.1/2" e demais e acessórios)',null,3200.0,1600.0,null,null),
('Caixa de passagem (Caixa 4 x 2 , Caixa 4 x 4, Caixa 15 x 15, Caixa 20 x 20, Caixa 30 x 30, etc...)','vb',358.9,179.45,null,null),
('Caixa de som aparente','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Caixa de som embutida','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Cavalete para hidrômetro','cj',null,null,null,null),
('Central de detecção e alarme, digital enderecável  com 2 laços (Completa com baterias, etc...)','pç',null,null,null,null),
('Chave fluxo ø 4"','pç',null,null,null,null),
('Chave fluxo ø 6"','pç',null,null,null,null),
('Chave seccionadora tripolar, abertura com carga, com base para fusível HH em 15Kv-400A com Kirk e eixo prolongador.','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Chuveiro automático (bico de sprinkler) de 1/2", tipo pendente, K80, com canopla','pç',44.78,26.868,null,null),
('Chuveiro automático (bico de sprinkler) de 1/2", tipo up-right, K80, sem canopla','pç',null,null,null,null),
('Chuveiro elétrico','pç',null,null,null,null),
('Condulete de alumínio Ø 1"','pç',28.93,17.358,null,null),
('Condulete de alumínio Ø 1.1/2"','pç',51.82,31.092,null,null),
('Condulete de alumínio Ø 1.1/4"','pç',null,null,null,null),
('Condulete de alumínio Ø 1/2"','pç',null,null,null,null),
('Condulete de alumínio Ø 2"','pç',null,null,null,null),
('Condulete de alumínio Ø 2.1/2"','pç',null,null,null,null),
('Condulete de alumínio Ø 3/4"','pç',15.83,9.498,null,null),
('Condulete de alumínio Ø4"','pç',null,null,null,null),
('Conexões','vb',null,null,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø1"          (Luva, Bucha,Curva, Plug, Tê, Cotovelos, joelhos, Niple, etc...)','vb',23.92,11.96,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø1.1/2"       (Luva, Bucha,Curva, Plug, Tê, Cotovelos, joelhos, Niple, etc...)','vb',57.16,28.58,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø1.1/4"       (Luva, Bucha,Curva, Plug, Tê, Cotovelos, joelhos, Niple, etc...)','vb',41.16,20.58,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø1/2"         (Luva, Bucha,Curva, Plug, Tê, Cotovelos, joelhos, Niple, etc...)','vb',10.45,5.225,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø2"       (Luva, Bucha,Curva, Plug, Tê, Cotovelos, joelhos, Niple, etc...)','vb',97.3,48.65,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø2.1/2"       (Luva,Curva, Cap, Tê, etc...)','vb',32.65,16.325,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø3"       (Luva,Curva, Cap, Tê, etc...)','vb',35.7,17.85,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø4"       (Luva,Curva, Cap, Tê, etc...)','vb',47.28,23.64,null,null),
('Conexões em ferro maleável em ferro maleável, classe 10, Tupy, Ø6"       (Luva,Curva, Cap, Tê, etc...)','vb',88.66,44.33,null,null),
('Conexões PVC  marrom soldável Ø 25 mm                                        (Joelho, Luva, União, tê, bucha, etc...)','vb',null,null,null,null),
('Conexões PVC  marrom soldável Ø 32 mm                                        (Joelho, Luva, União, tê, bucha, etc...)','vb',null,null,null,null),
('Conexões PVC  marrom soldável Ø 40 mm                                        (Joelho, Luva, União, tê, bucha, etc...)','vb',null,null,null,null),
('Conexões PVC  marrom soldável Ø 50 mm                                        (Joelho, Luva, União, tê, bucha, etc...)','vb',null,null,null,null),
('Conexões PVC  marrom soldável Ø 60 mm                                        (Joelho, Luva, União, tê, bucha, etc...)','vb',null,null,null,null),
('Conexões PVC Azul                                                                                               ( Joelho, Tê, luva, etc...) Ø 25 mm X 1/2",Ø 25 mm X3/4", Etc...','vb',null,null,null,null),
('Conexões PVC série R Ø 100 mm (Joelho, Junção, Junço, Tê, redução, luva, cap, etc...)','vb',null,null,null,null),
('Conexões PVC série R Ø 150 mm (Joelho, Junção, Junço, Tê, redução, luva, cap, etc...)','vb',null,null,null,null),
('Conexões PVC série R Ø 40 mm ( Joelho, Junção, Junço, Tê, redução, luva, cap, etc...)','vb',null,null,null,null),
('Conexões PVC série R Ø 50 mm (Joelho, Junção, Junço, Tê, redução, luva, cap, etc...)','vb',null,null,null,null),
('Conexões PVC série R Ø 75 mm (Joelho, Junção, Junço, Tê, redução, luva, cap, etc...)','vb',null,null,null,null),
('Conjunto de 2 Interruptores simples montado em caixa 4x2"','pç',null,null,null,null),
('Conjunto de 2 Interruptores simples montado em condulete','pç',null,null,null,null),
('Conjunto de Dector Linear - Emissor e receptor . Ref. DFL 3100 Intelbras','cj',null,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('Conjunto de tomada dupla para telefone/Lógica Rj-45 Montado em condulete','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Conjunto de tomada para telefone Rj-11 Montado em caixa 4x2"','pç',null,null,null,null),
('Conjunto de tomada para telefone Rj-11 Montado em condulete','pç',null,null,null,null),
('Conjunto de tomada para telefone/Lógica Rj-45 Montado em caixa 4x2"','pç',114.6,68.76,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Conjunto de tomada para telefone/Lógica Rj-45 Montado em condulete','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('CONTROLE DE DEMANDA',null,null,null,null,null),
('Cuba oval de embutir completa, com válvula, sifão cromado, torneira e rabicho','pç',null,null,null,null),
('Curva 90º galvanizada a fogo Ø 3/4"','pç',null,null,null,null),
('Curva 90º galvanizada á fogo  Ø 1.1/4"','pç',null,null,null,null),
('Curva 90º galvanizada á fogo  Ø 1/2"','pç',null,null,null,null),
('Câmera contadora de fluxo','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Câmera de segurança do tipo DOME Sistema CFTV a realocar','pç',null,null,null,null),
('Câmera fixa de segurança Sistema CFTV a realocar','pç',50.0,null,null,null),
('Despesas Mensais (Mão de Obra)',null,null,null,'224650','2.0 Administração'),
('Detector de fumaça endereçável, inclusive base e demais acessórios','pç',null,null,null,null),
('Detector de temperatura (termovelocimétrico), . inclusive base e demais acessórios','pç',null,null,null,null),
('Dias',null,null,null,null,null),
('DISTRIBUIÇÃO DE ILUMINAÇÃO E TOMADAS',null,null,null,null,null),
('DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)',null,null,null,null,null),
('DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS',null,null,null,null,null),
('Ducha higiênica','pç',null,null,null,null),
('Elaboração dos desenhos como construído (As-builts)','vb',1.0,1250.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Eletricista',null,45.6,null,'224650','1.0 Homem/Hora'),
('Eletrocalha galvanizada lisa com tampa de encaixe 100x100mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 100x50mm','m',25.71,15.426,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 150x100mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 150x50mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 200x100mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 300x100mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 300x75mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 400x100mm','m',null,null,null,null),
('Eletrocalha galvanizada lisa com tampa de encaixe 50x50mm','m',null,null,null,null),
('Eletroduto de ferro galvanizado Ø 1"','m',32.08,19.248,null,null),
('Eletroduto de ferro galvanizado Ø 1.1/2"','m',50.91,30.546,null,null),
('Eletroduto de ferro galvanizado Ø 1.1/4"','m',null,null,null,null),
('Eletroduto de ferro galvanizado Ø 1/2"','m',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Eletroduto de ferro galvanizado Ø 2"','m',null,null,null,null),
('Eletroduto de ferro galvanizado Ø 2.1/2"','m',null,null,null,null),
('Eletroduto de ferro galvanizado Ø 3/4"','m',15.02,9.012,null,null),
('Eletroduto de ferro galvanizado Ø 4"','m',null,null,null,null),
('Encanador',null,46.8,null,'224650','1.0 Homem/Hora'),
('Encarregado Eletrica e hidraulica',null,70.8,null,'224650','1.0 Homem/Hora'),
('Encarregado hidraulica',null,null,null,'224650','1.0 Homem/Hora'),
('Engenheiro','vb',4.0,14000.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Extintor Gás Carbônico (CO2) 6kg','un',null,null,null,null),
('Extintor Pó Químico 4 kg (ABC)','un',null,null,null,null),
('Extintor Pó Químico 6kg (ABC)','un',325.0,162.5,null,null),
('Extintor Pó Químico 6kg (ABC) realocado','un',null,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('Extintor Água Pressurizada 10Litros','un',null,null,null,null),
('Filtro para pia','pç',null,null,null,null),
('FORNECIMENTO  E INSTALAÇÃO DE EXTINTORES',null,null,null,null,null),
('FORNECIMENTO E INSTALAÇÃO DE SISTEMA DE DETECÇÃO E ALARME E ILUMINAÇÃO DE EMERGENCIA',null,null,null,null,null),
('Fusível limitador de corrente HH-15Kv - 50A','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Gambiarra da obra e ligação de equipamentos (iluminação e tomadas)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Grade metálica fixa e removível','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Grelha inox 15X15','pç',null,null,null,null),
('Hidrômetro Ø 1.1/2"','pç',null,null,null,null),
('Hidrômetro Ø 1.1/4"','pç',null,null,null,null),
('Instalar 1 (um) conjunto DPS classe II em cada um dos cinco quadros parciais existentes.','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Instalar 1 dispositivos bipolares DR DE 25A/30mA no painel existente QLT-T','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Instalação de luminária LED marquise (Somente mão de obra)','pç',null,null,null,null),
('Instalação de luminária LED nos provadores (Somente mão de obra)','pç',70.0,null,null,null),
('Instalação de luminária LED wallwasher (Somente mão de obra)','pç',29.5,null,null,null),
('Instalação de Spots LED em trilho eletrificado (Somente mão de obra)','pç',29.5,null,null,null),
('Instalação de Spots LED embutidos no forro (Somente mão de obra)','pç',29.5,null,null,null),
('Instalação de transformador a seco de 500kVA - 13.8kV/380/220V (Somente mão de obra)','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Instalação do painel de senha no RFS (painel e cabo de rede fornecida pela C&A Modas)','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Instalação Luminária de sobrepor (Somente mão de obra)','pç',null,null,null,null),
('Instalação Trilho Eletrificado (Somente mão de obra)','pç',29.5,null,null,null),
('Interruptor Itermediário montado em condulete','pç',null,null,null,null),
('Interruptor paralelo montado em caixa 4x2"','pç',null,null,null,null),
('Interruptor paralelo montado em condulete','pç',50.17,30.102,null,null),
('Interruptor simples montado em caixa 4x2"','pç',34.31,20.586,null,null),
('Interruptor simples montado em condulete','pç',30.08,18.048,null,null),
('Interruptor triplo montado em caixa 4x2"','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Isolador 15Kv','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Kit para drenagem composto por registro de gaveta de 1", manômetro, etc.',null,null,null,null,null),
('LINEAR DE LED EMBUTIDA','pç',32.5,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('LOGO C&A CAIXAS','pç',120.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('LOUÇAS E METAIS',null,null,null,null,null),
('luminaria GAP embutir','pç',32.5,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('luminaria lustre beleza','pç',70.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Luminária administrativa 1x28W (Somente mão de obra)','pç',null,null,null,null),
('Luminária administrativa 2x28W (Somente mão de obra)','pç',null,null,null,null),
('LUMINÁRIA BALIZADORA (PROVADOR)','pç',32.5,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Luminária blindada "tipo tartaruga" com grade e corpo de alumínio fundido, soquete E-27 com lâmpada','pç',null,null,null,null),
('LUMINÁRIA ENTRE RIPADO CAIXAS','pç',50.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('LUSTRE PROVADOR','pç',70.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Lâmpada montada no  forro ou perfilado (Somente mão de obra)','pç',null,null,null,null),
('Materiais',null,null,null,'224650','2.0 Administração'),
('Materiais de consumo (lâminas de serra, brocas, estopas, etc.)','vb',2200.0,1100.0,null,null),
('Materiais para solda (argônio, oxigênio, acetileno, varetas, equipamentos, etc.)','vb',3500.0,1750.0,null,null),
('Meio Oficial Eletrico',null,34.8,null,'224650','1.0 Homem/Hora'),
('Mictório completo','pç',null,null,null,null),
('Mufla interna # 35 mm² / 15 KV','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Módulo de entrada/saída - MI 521 Intelbras','pç',null,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('OUTROS OMISSOS',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Para raio tipo polimérico 13.8 kV / 10kA, inclusive suporte de fixação','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Parafuso e bucha borboleta','vb',3000.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Passagens e transporte','vb',4.0,8900.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('PENDENTE ENTRADA PROVADOR','pç',80.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('PERFIL DE LED BORDA DA SANCA PROVADOR','pç',70.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Perfilado galvanizado liso 38x38mm','m',13.18,7.908,null,null),
('Pia de cozinha completa, com torneira, válvula e sifão cromado','pç',null,null,null,null),
('Pintura de tubulação (primer, esmalte sintético, todos c/02 demãos), 2.1/2" e 3"','m',12.0,7.2,null,null),
('Pintura de tubulação (primer, esmalte sintético, todos com 02 demãos), até 2"','m',12.0,7.2,null,null),
('Pintura de tubulação (primer, esmalte sintético, todos com 02 demãos), até 4"','m',null,null,null,null),
('Pintura de tubulação (primer, esmalte sintético, todos com 02 demãos), até 6"','m',null,null,null,null),
('Plataforma tipo Sanfona / Andaimes','vb',4.0,3000.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Plug monobloco 2P+T fêmea','pç',5.05,3.03,null,null),
('Ponto de chuveiro elétrico','pç',null,null,null,null),
('Ponto de torneira elétrica','pç',null,null,null,null),
('Ponto para câmera de CFTV','un',50.0,null,null,null),
('Ponto para câmera do contador de fluxo','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Potenciometro de som','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Prensa cabo de Ø 1/2"','pç',5.35,3.21,null,null),
('Q. REVERSÃO NOBREAK CENTRAL','pç',null,null,null,null),
('QAC - 2A','pç',null,null,null,null),
('QDAC - 3','pç',null,null,null,null),
('QDC - 1A','pç',null,null,null,null),
('QGBT - E( medidores com portas serial RS485- vide pasta lista de medidores compativeis)','pç',null,null,null,null),
('QGBT - N ( medidores com portas serial RS485- vide pasta lista de medidores compativeis)','pç',null,null,null,null),
('QLE-1A','pç',null,null,null,null),
('QLE-2','pç',null,null,null,null),
('QLE-3','pç',null,null,null,null),
('QLE-T','pç',null,null,null,null),
('QLT-1A','pç',null,null,null,null),
('QLT-2','pç',null,null,null,null),
('QLT-3','pç',null,null,null,null),
('QLT-T','pç',null,null,null,null),
('QNB-1A','pç',null,null,null,null),
('Quadro Banco de Capacitor','pç',null,null,null,null),
('QUADRO BLOQUEIO GERADOR','pç',null,null,null,null),
('Quadro de distribuição 60x60x12cm','pç',null,null,null,null),
('Quadro de distribuição 80x80x12cm','pç',null,null,null,null),
('QUADROS GERAIS, PARCIAIS E NOBREAK´S',null,null,null,null,null),
('Ralo Sifonado 100X100X50mm','pç',null,null,null,null),
('Ralo Sifonado 150X185X75mm','pç',null,null,null,null),
('Realocação dos quadros existentes do pavimento térreo.','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('REDE DE ALIMENTADORES CONDICIONADORES DE AR',null,null,null,null,null),
('REDE DE ALIMENTADORES QUADROS',null,null,null,null,null),
('REDE DE ESGOTO SANITÁRIO',null,null,null,null,null),
('REDE DE HIDRANTES E CHUVEIROS AUTOMÁTICOS',null,null,null,null,null),
('Reforma do QGBT com a inclusão de 2 disjuntores tripolares de 63A','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Registro de gaveta bruto Ø 1 ''''','pç',null,null,null,null),
('Registro de gaveta bruto Ø 1 1/2''''','pç',null,null,null,null),
('Registro de gaveta bruto Ø 1.1/4''''','pç',null,null,null,null),
('Registro de gaveta bruto Ø 2"','pç',null,null,null,null),
('Registro de gaveta bruto Ø 3/4"','pç',null,null,null,null),
('Registro de gaveta cromado Ø 1 1/2''''','pç',null,null,null,null),
('Registro de gaveta cromado Ø 1"','pç',null,null,null,null),
('Registro de gaveta cromado Ø 1.1/4''''','pç',null,null,null,null),
('Registro de gaveta cromado Ø 3/4"','pç',null,null,null,null),
('Registro de gaveta em ferro fundido, com haste ascendente, de 4"','pç',null,null,null,null),
('Registro de gaveta em ferro fundido, com haste ascendente, de 6"','pç',null,null,null,null),
('Registro de pressão cromado Ø 3/4"','pç',null,null,null,null),
('Remoçao de chuveiro automático pendente.','pç',70.0,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('Remoção de detector de fumaça','pç',70.0,null,'224650','21.0 SISTEMA DE PREVENÇÃO E COMBATE A INCÊNDIO'),
('Remoção de luminarias','vb',4000.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Remoção de perfilados','vb',2500.0,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Sealtube ø1.1/2"','m',25.2,15.12,null,null),
('Sealtube ø2"','m',null,null,null,null),
('Sealtube ø3/4"','m',null,null,null,null),
('Sensor de presença','pç',88.11,52.866,null,null),
('Sensor de temperatura','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Sensor IVP- Infravermelho Passivo em Condulete','pç',50.0,null,null,null),
('Sensor magnético porta','pç',null,null,null,null),
('Sinalização de extintores e de segurança em geral (CONFORME NORMAS LOCAIS DO CBM)','vb',30.03,10.015,null,null),
('Sirene bitonal, inclusive base e demais acessórios','pç',null,null,null,null),
('Sirene de Alarme','pç',null,null,null,null),
('SISTEMA DE CFTV E SENSORES',null,null,null,null,null),
('SISTEMA DE CONTADOR FLUXO',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Sistema de iluminação e tomadas para a subestação','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('SISTEMA DE LÓGICA',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('SISTEMA DE SONORIZAÇÃO',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Soldador',null,50.4,null,'224650','1.0 Homem/Hora'),
('SUBESTAÇÃO',null,null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Subwoofer','pç',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Suporte completo eletrodutos (tirantes, chumbadores, abraçadeiras, etc.)','vb',645.61,322.805,null,null),
('Suporte completo para eletrocalhas, perfilados e eletrodutos (tirantes, chumbadores, abraçadeiras, ganchos, etc.)','vb',3965.44,1982.72,null,null),
('Suporte completo para eletrodutos (tirantes, chumbadores, abraçadeiras, ganchos, etc.)','vb',null,null,null,null),
('Suporte completo para tubulação até 2" (tirantes, chumbadores, abraçadeiras,etc.)',null,7.56,4.536,null,null),
('Suporte completo para tubulação até 4" (tirantes, chumbadores, abraçadeiras,etc.)',null,null,null,null,null),
('Suporte completo para tubulação até 6" (tirantes, chumbadores, abraçadeiras,etc.)',null,null,null,null,null),
('Suporte completo para tubulação de 2.1/2" a 3"(tirantes, abraçadeiras,etc.)',null,9.89,5.934,null,null),
('Suporte metálico para (Mufla, Para-raios, Isoladores e demais acessórios)','un',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Tanque completo, com válvula, sifão cromado, torneira e rabicho','pç',null,null,null,null),
('Taxa de Desmobilização',null,null,null,'224650','2.0 Administração'),
('Taxa de Mobilização',null,null,null,'224650','2.0 Administração'),
('Terceiros',null,null,null,'224650','2.0 Administração'),
('Testes hidrostáticos conforme norma','vb',1750.0,875.0,null,null),
('Tomada 2P+T 32A - Steck','pç',303.15,181.89,null,null),
('Tomada dupla universal 2P+T miolo vermelho montado em caixa 4x2"  10A','pç',71.76,43.056,null,null),
('Tomada dupla universal 2P+T miolo vermelho montado em condulete   10A','pç',64.42,38.652,null,null),
('Tomada dupla universal 2P+T montado em condulete 10A','pç',null,null,null,null),
('Tomada específica Bacão Térmico','pç',null,null,null,null),
('Tomada tripla universal 2P+T miolo vermelho montado em caixa 4x2"  10A','pç',null,null,null,null),
('Tomada tripla universal 2P+T miolo vermelho montado em condulete   10A','pç',91.17,45.585,null,null),
('Tomada tripla universal 2P+T montado em condulete 10A','pç',null,null,null,null),
('Tomada universal 2P+T 20A + 1 interruptor simples montado em condulete','pç',null,null,null,null),
('Tomada universal 2P+T miolo vermelho montado em caixa 4x2"  10A','pç',50.11,30.066,null,null),
('Tomada universal 2P+T miolo vermelho montado em caixa 4x2"  20A','pç',null,null,null,null),
('Tomada universal 2P+T miolo vermelho montado em condulete   10A','pç',null,null,null,null),
('Tomada universal 2P+T miolo vermelho montado em condulete   20A','pç',null,null,null,null),
('Tomada universal 2P+T montado em caixa 4x2" 10A','pç',43.43,26.058,null,null),
('Tomada universal 2P+T montado em caixa 4x2" 20A','pç',null,null,null,null),
('Tomada universal 2P+T montado em condulete 10A','pç',27.7,16.62,null,null),
('Tomada universal 2P+T montado em condulete 20A','pç',30.56,18.336,null,null),
('Torneira de lavagem','pç',null,null,null,null),
('Torneira Presmatic p/ lavatório COM AREJADOR','pç',null,null,null,null),
('Transporte (fretes de materiais)','vb',4.0,4500.0,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Transporte vertical / horizontal','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Tubo aço carbono preto Din 2440,com costura, de  Ø2.1/2"','m',102.28,61.368,null,null),
('Tubo aço carbono preto Din 2440,com costura, de  Ø3"','m',null,null,null,null),
('Tubo aço carbono preto Din 2440,com costura, de  Ø4"','m',null,null,null,null),
('Tubo aço carbono preto Din 2440,com costura, de  Ø6"','m',null,null,null,null),
('Tubo de PVC esgoto, reforçado série R, incluindo conexões Ø 100mm','m',null,null,null,null),
('Tubo de PVC esgoto, reforçado série R, incluindo conexões Ø 150mm','m',null,null,null,null),
('Tubo de PVC esgoto, reforçado série R, incluindo conexões Ø 40mm','m',null,null,null,null),
('Tubo de PVC esgoto, reforçado série R, incluindo conexões Ø 50mm','m',null,null,null,null),
('Tubo de PVC esgoto, reforçado série R, incluindo conexões Ø 75mm','m',null,null,null,null),
('Tubo de PVC marrom soldável, incluindo conexões Ø 25mm','m',null,null,null,null),
('Tubo de PVC marrom soldável, incluindo conexões Ø 32mm','m',null,null,null,null),
('Tubo de PVC marrom soldável, incluindo conexões Ø 40mm','m',null,null,null,null),
('Tubo de PVC marrom soldável, incluindo conexões Ø 50mm','m',null,null,null,null),
('Tubo de PVC marrom soldável, incluindo conexões Ø 60mm','m',null,null,null,null),
('Tubo de PVC Ø100mm para o sistema de correio pneumático, inclusive conexões, suportes e ligações.','m',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Tubo ferro galvanizado Din 2440, com costura, de  Ø1"','m',34.2,17.1,null,null),
('Tubo ferro galvanizado Din 2440, com costura, de  Ø1.1/2"','m',57.05,34.23,null,null),
('Tubo ferro galvanizado Din 2440, com costura, de  Ø1.1/4"','m',44.21,26.526,null,null),
('Tubo ferro galvanizado Din 2440, com costura, de  Ø2"','m',72.15,43.29,null,null),
('TUBULAÇÃO SERIE "R" PARA SISTEMA DE CORREIO PNEUMÁTICO','vb',null,null,'224650','15.0 SERVIÇOS COMUNS A TODAS AS INSTALAÇÕES'),
('Verba de miudezas e fixações','vb',1500.0,750.0,null,null),
('Verba para miudezas e fixações','vb',678.14,339.07,null,null),
('Verba para miudezas, acessorios e fixações','vb',314.81,188.886,null,null),
('Verba para miudezas, pintura e fixações','vb',null,null,null,null),
('ÁGUA FRIA',null,null,null,null,null)
on conflict (descricao) do update set unidade=excluded.unidade, mat_unit=excluded.mat_unit, mobra_unit=excluded.mobra_unit, classe_custo=excluded.classe_custo, secao=excluded.secao;

insert into public.miudezas_regras (material_base,miudeza,tipo_verba,coef,valor_unit,usar,sistema,familia) values
('Eletroduto de ferro galvanizado Ø 3/4"','Unidut reto galvanizado Ø 3/4"','Conexoes/acessorios',0.16666667,3.9,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','Unidut reto galvanizado Ø 1"','Conexoes/acessorios',0.16666667,4.451,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Condulete de alumínio Ø 3/4"','Unidut cônico galvanizado Ø 3/4" (box)','Conexoes/acessorios',2.0,3.55,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Condulete'),
('Condulete de alumínio Ø 1"','Unidut cônico galvanizado Ø 1" (box)','Conexoes/acessorios',2.0,2.8,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Condulete'),
('Condulete de alumínio Ø 3/4"','Arruela Ø 3/4"','Miudezas/consumiveis',2.0,0.85,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Condulete'),
('Condulete de alumínio Ø 1"','Arruela Ø 1"','Miudezas/consumiveis',2.0,1.2393,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Condulete'),
('Eletroduto de ferro galvanizado Ø 3/4"','Abraçadeira tipo D 3/4','Fixacoes/suportes',0.66666667,0.88,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Curva para eletroduto Ø 3/4"','Curva para eletroduto Ø 3/4"','Conexoes/acessorios',1.0,3.86,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Curva para eletroduto Ø 1"','Curva para eletroduto Ø 1"','Conexoes/acessorios',1.0,3.4232,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 3/4"','Barra roscada 1/4','Fixacoes/suportes',0.33333333,5.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','Barra roscada 1/4','Fixacoes/suportes',0.33333333,5.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('eletrocalha 150x100mm','Barra roscada 1/4','Fixacoes/suportes',0.33333333,5.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 100x50mm','Barra roscada 1/4','Fixacoes/suportes',0.33333333,5.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Perfilado liso 38x38','Barra roscada 1/4','Fixacoes/suportes',0.33333333,5.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('Eletroduto de ferro galvanizado Ø 3/4"','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.52,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.52,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('eletrocalha 150x100mm','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.52,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 100x50mm','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.52,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Perfilado liso 38x38','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.52,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('Eletroduto de ferro galvanizado Ø 3/4"','PORCA 1/4','Miudezas/consumiveis',3.33333333,0.45,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','PORCA 1/4','Miudezas/consumiveis',2.0,0.45,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('eletrocalha 150x100mm','PORCA 1/4','Miudezas/consumiveis',2.0,0.45,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 100x50mm','PORCA 1/4','Miudezas/consumiveis',2.0,0.45,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Perfilado liso 38x38','PORCA 1/4','Miudezas/consumiveis',2.0,0.45,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('Eletroduto de ferro galvanizado Ø 3/4"','arruela 1/4','Miudezas/consumiveis',3.33333333,0.4,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','arruela 1/4','Miudezas/consumiveis',2.0,0.4,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('eletrocalha 150x100mm','arruela 1/4','Miudezas/consumiveis',2.0,0.4,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 100x50mm','arruela 1/4','Miudezas/consumiveis',2.0,0.4,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Perfilado liso 38x38','arruela 1/4','Miudezas/consumiveis',2.0,0.4,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('Eletroduto de ferro galvanizado Ø 3/4"','parafuso lentilha 1/4','Miudezas/consumiveis',2.0,0.39,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1"','parafuso lentilha 1/4','Miudezas/consumiveis',2.0,0.39,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletroduto'),
('Perfilado liso 38x38','parafuso lentilha 1/4','Miudezas/consumiveis',2.0,0.39,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('eletrocalha 150x100mm','Suporte Eletrocalha 150x100','Fixacoes/suportes',0.5,4.68,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 150x100mm','Emenda Eletrocalha 150x100','Conexoes/acessorios',0.5,3.36,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('eletrocalha 100x50mm','Emenda Eletrocalha 100x100','Conexoes/acessorios',0.5,2.87,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Saida de eletrocalha 150x100mm para perfilado 38x38','Saida de eletrocalha para perfilado 38x38','Conexoes/acessorios',1.0,2.37,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Eletrocalha'),
('Perfilado liso 38x38','SUPORTE 38x38','Fixacoes/suportes',0.5,1.4299,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('EMENDA T interna 38x38','EMENDA T interna 38x38','Conexoes/acessorios',0.16666667,2.6647,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Outros'),
('Saida de perfilado para eletroduto 3/4 #18 PZ','Saida de perfilado para eletroduto 3/4 #18 PZ','Conexoes/acessorios',1.0,2.8,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('GANCHO CURTO P/ PERFILADO 38X38 #18 PZ','GANCHO CURTO P/ PERFILADO 38X38 #18 PZ','Fixacoes/suportes',1.0,1.23,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('EMENDA INTERNA I ACO P/PERFILADO 38X38 PRE ZINC #22','EMENDA INTERNA I ACO P/PERFILADO 38X38 PRE ZINC #22','Conexoes/acessorios',1.0,1.25,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Perfilado'),
('CURVA V.E.90 PERFIL.38X38 ZINC.','CURVA VERTICAL EXTERNA .90 PERFIL.38X38 ZINC.','Conexoes/acessorios',1.0,5.9,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Outros'),
('CURVA V.E.90 PERFIL.38X38 ZINC.','CURVA VERTICAL INTERNA .90 PERFIL.38X38 ZINC.','Conexoes/acessorios',1.0,5.5,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Outros'),
('Cabo cobre isolação afumex 750V #2,5mm²','Fita isolante','Miudezas/consumiveis',0.05,4.5,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #2,5mm²','Fita crepe','Miudezas/consumiveis',0.02,5.0,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #2,5mm²','Solda estranho','Miudezas/consumiveis',0.01,18.0,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #2,5mm²','Identificador','Miscelaneas',1.0,0.3,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #2,5mm²','Terminais 2,5m','Miscelaneas',2.0,0.22,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #4mm²','Terminais 4,0m','Miscelaneas',2.0,0.3,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #6mm²','Terminais 6,0m','Miscelaneas',2.0,0.38,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('Cabo cobre isolação afumex 750V #2,5mm²','Luvas de emenda','Conexoes/acessorios',0.2,0.8,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Cabos'),
('CAIXA 4X2','Caixa 4x2" com espelho cego','Miscelaneas',1.0,6.44,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Caixas'),
('CAIXA 4X2','SUPORTE 4X2','Fixacoes/suportes',1.0,1.95,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Caixas'),
('CAIXA 4X2','PLACA 4X2','Miscelaneas',1.0,6.44,true,'2.0 - DISTRIBUIÇÃO DE TOMADAS ESTABILIZADAS','Caixas'),
('Eletroduto de ferro galvanizado Ø 1.1/4"','Unidut reto galvanizado Ø 1.1/4"','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 1.1/2"','Unidut reto galvanizado Ø 1.1/2"','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 2"','Unidut reto galvanizado Ø 2"','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 2.1/2"','Unidut reto galvanizado Ø 2.1/2"','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletroduto'),
('Eletroduto de ferro galvanizado Ø 4"','Unidut reto galvanizado Ø 4"','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletroduto'),
('Condulete de alumínio Ø 1.1/4"','Unidut cônico galvanizado Ø 1.1/4" (box)','Conexoes/acessorios',2.0,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Condulete'),
('Condulete de alumínio Ø 1.1/2"','Unidut cônico galvanizado Ø 1.1/2" (box)','Conexoes/acessorios',2.0,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Condulete'),
('eletrocalha 100x100','Barra roscada 1/4','Fixacoes/suportes',0.33333333,11.85,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 50x50mm','Barra roscada 1/4','Fixacoes/suportes',0.33333333,11.85,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 300x75mm','Barra roscada 1/4','Fixacoes/suportes',0.33333333,11.85,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 200x50mm','Barra roscada 1/4','Fixacoes/suportes',0.33333333,11.85,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 100x100','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 50x50mm','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 300x75mm','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 200x50mm','jaqueta e cone 1/4','Fixacoes/suportes',0.33333333,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 300x75mm','Suporte Eletrocalha 300x75','Fixacoes/suportes',0.5,6.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 200x50mm','Suporte Eletrocalha 200x50','Fixacoes/suportes',0.5,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 100x50mm','Suporte Eletrocalha 100x100','Fixacoes/suportes',0.5,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 100x100','Suporte Eletrocalha 100x50','Fixacoes/suportes',0.5,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 50x50mm','Suporte Eletrocalha 50x50','Fixacoes/suportes',0.5,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 300x75mm','Emenda Eletrocalha 300x75','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('eletrocalha 200x50mm','Emenda Eletrocalha 200x50','Conexoes/acessorios',0.16666667,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Eletrocalha'),
('Saida de perfilado para eletroduto 1 #18 PZ','Saida de perfilado para eletroduto 1 #18 PZ','Conexoes/acessorios',1.0,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Perfilado'),
('Saida de perfilado para eletroduto 1.1/4 #18 PZ','Saida de perfilado para eletroduto 1.1/4 #18 PZ','Conexoes/acessorios',1.0,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Perfilado'),
('Saida de perfilado para eletroduto 1.1/2 #18 PZ','Saida de perfilado para eletroduto 1.1/2 #18 PZ','Conexoes/acessorios',1.0,0.0,true,'3.0 - DISTRIBUIÇÃO DE TELEFONIA (40 PONTOS)','Perfilado'),
('eletrocalha 100x100','Emenda Eletrocalha 100x50','Conexoes/acessorios',0.16666667,0.0,true,'4.0 - SISTEMA DE CFTV E SENSORES','Eletrocalha'),
('Perfilado liso 38x38','EMENDA T interna 38x38','Conexoes/acessorios',0.16666667,0.0,true,'9.0 - REDE DE ALIMENTADORES QUADROS','Perfilado')
on conflict (material_base, miudeza, tipo_verba) do update set coef=excluded.coef, valor_unit=excluded.valor_unit, usar=excluded.usar, sistema=excluded.sistema, familia=excluded.familia;

commit;